[package]
name = "framelabs-s3-server"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
aws-config = { version = "1", default-features = false, features = [
    "behavior-version-latest",
    "rt-tokio",
    "client-hyper",
    "rustls",
] }
aws-credential-types = "1"
aws-sdk-s3 = { version = "1", features = ["behavior-version-latest"] }
aws-smithy-types-convert = { version = "0.60", features = ["convert-chrono"] }
axum = { version = "0.7", features = ["macros"] }
image = { version = "0.25" }
libheif-rs = "1"
rand = "0.8.5"
tokio = { version = "1", features = ["full"] }
flate2 = "1"
serde = { version = "1", features = ["derive"] }
